//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.10 at 10:41:43 AM KST 
//


package net.opengis.citygml.bridge.v_2_0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.opengis.citygml.bridge.v_2_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AbstractBridge_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "_AbstractBridge");
    private final static QName _GenericApplicationPropertyOfAbstractBridge_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "_GenericApplicationPropertyOfAbstractBridge");
    private final static QName _Bridge_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "Bridge");
    private final static QName _GenericApplicationPropertyOfBridge_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "_GenericApplicationPropertyOfBridge");
    private final static QName _BridgePart_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "BridgePart");
    private final static QName _GenericApplicationPropertyOfBridgePart_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "_GenericApplicationPropertyOfBridgePart");
    private final static QName _BridgeInstallation_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "BridgeInstallation");
    private final static QName _GenericApplicationPropertyOfBridgeInstallation_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "_GenericApplicationPropertyOfBridgeInstallation");
    private final static QName _IntBridgeInstallation_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "IntBridgeInstallation");
    private final static QName _GenericApplicationPropertyOfIntBridgeInstallation_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "_GenericApplicationPropertyOfIntBridgeInstallation");
    private final static QName _BridgeConstructionElement_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "BridgeConstructionElement");
    private final static QName _GenericApplicationPropertyOfBridgeConstructionElement_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "_GenericApplicationPropertyOfBridgeConstructionElement");
    private final static QName _BoundarySurface_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "_BoundarySurface");
    private final static QName _GenericApplicationPropertyOfBoundarySurface_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "_GenericApplicationPropertyOfBoundarySurface");
    private final static QName _RoofSurface_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "RoofSurface");
    private final static QName _GenericApplicationPropertyOfRoofSurface_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "_GenericApplicationPropertyOfRoofSurface");
    private final static QName _WallSurface_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "WallSurface");
    private final static QName _GenericApplicationPropertyOfWallSurface_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "_GenericApplicationPropertyOfWallSurface");
    private final static QName _GroundSurface_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "GroundSurface");
    private final static QName _GenericApplicationPropertyOfGroundSurface_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "_GenericApplicationPropertyOfGroundSurface");
    private final static QName _ClosureSurface_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "ClosureSurface");
    private final static QName _GenericApplicationPropertyOfClosureSurface_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "_GenericApplicationPropertyOfClosureSurface");
    private final static QName _OuterFloorSurface_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "OuterFloorSurface");
    private final static QName _GenericApplicationPropertyOfOuterFloorSurface_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "_GenericApplicationPropertyOfOuterFloorSurface");
    private final static QName _OuterCeilingSurface_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "OuterCeilingSurface");
    private final static QName _GenericApplicationPropertyOfOuterCeilingSurface_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "_GenericApplicationPropertyOfOuterCeilingSurface");
    private final static QName _FloorSurface_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "FloorSurface");
    private final static QName _GenericApplicationPropertyOfFloorSurface_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "_GenericApplicationPropertyOfFloorSurface");
    private final static QName _InteriorWallSurface_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "InteriorWallSurface");
    private final static QName _GenericApplicationPropertyOfInteriorWallSurface_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "_GenericApplicationPropertyOfInteriorWallSurface");
    private final static QName _CeilingSurface_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "CeilingSurface");
    private final static QName _GenericApplicationPropertyOfCeilingSurface_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "_GenericApplicationPropertyOfCeilingSurface");
    private final static QName _Opening_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "_Opening");
    private final static QName _GenericApplicationPropertyOfOpening_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "_GenericApplicationPropertyOfOpening");
    private final static QName _Window_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "Window");
    private final static QName _GenericApplicationPropertyOfWindow_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "_GenericApplicationPropertyOfWindow");
    private final static QName _Door_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "Door");
    private final static QName _GenericApplicationPropertyOfDoor_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "_GenericApplicationPropertyOfDoor");
    private final static QName _BridgeRoom_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "BridgeRoom");
    private final static QName _GenericApplicationPropertyOfBridgeRoom_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "_GenericApplicationPropertyOfBridgeRoom");
    private final static QName _BridgeFurniture_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "BridgeFurniture");
    private final static QName _GenericApplicationPropertyOfBridgeFurniture_QNAME = new QName("http://www.opengis.net/citygml/bridge/2.0", "_GenericApplicationPropertyOfBridgeFurniture");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.opengis.citygml.bridge.v_2_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BridgeType }
     * 
     */
    public BridgeType createBridgeType() {
        return new BridgeType();
    }

    /**
     * Create an instance of {@link BridgePartType }
     * 
     */
    public BridgePartType createBridgePartType() {
        return new BridgePartType();
    }

    /**
     * Create an instance of {@link BridgeInstallationType }
     * 
     */
    public BridgeInstallationType createBridgeInstallationType() {
        return new BridgeInstallationType();
    }

    /**
     * Create an instance of {@link IntBridgeInstallationType }
     * 
     */
    public IntBridgeInstallationType createIntBridgeInstallationType() {
        return new IntBridgeInstallationType();
    }

    /**
     * Create an instance of {@link BridgeConstructionElementType }
     * 
     */
    public BridgeConstructionElementType createBridgeConstructionElementType() {
        return new BridgeConstructionElementType();
    }

    /**
     * Create an instance of {@link RoofSurfaceType }
     * 
     */
    public RoofSurfaceType createRoofSurfaceType() {
        return new RoofSurfaceType();
    }

    /**
     * Create an instance of {@link WallSurfaceType }
     * 
     */
    public WallSurfaceType createWallSurfaceType() {
        return new WallSurfaceType();
    }

    /**
     * Create an instance of {@link GroundSurfaceType }
     * 
     */
    public GroundSurfaceType createGroundSurfaceType() {
        return new GroundSurfaceType();
    }

    /**
     * Create an instance of {@link ClosureSurfaceType }
     * 
     */
    public ClosureSurfaceType createClosureSurfaceType() {
        return new ClosureSurfaceType();
    }

    /**
     * Create an instance of {@link OuterFloorSurfaceType }
     * 
     */
    public OuterFloorSurfaceType createOuterFloorSurfaceType() {
        return new OuterFloorSurfaceType();
    }

    /**
     * Create an instance of {@link OuterCeilingSurfaceType }
     * 
     */
    public OuterCeilingSurfaceType createOuterCeilingSurfaceType() {
        return new OuterCeilingSurfaceType();
    }

    /**
     * Create an instance of {@link FloorSurfaceType }
     * 
     */
    public FloorSurfaceType createFloorSurfaceType() {
        return new FloorSurfaceType();
    }

    /**
     * Create an instance of {@link InteriorWallSurfaceType }
     * 
     */
    public InteriorWallSurfaceType createInteriorWallSurfaceType() {
        return new InteriorWallSurfaceType();
    }

    /**
     * Create an instance of {@link CeilingSurfaceType }
     * 
     */
    public CeilingSurfaceType createCeilingSurfaceType() {
        return new CeilingSurfaceType();
    }

    /**
     * Create an instance of {@link WindowType }
     * 
     */
    public WindowType createWindowType() {
        return new WindowType();
    }

    /**
     * Create an instance of {@link DoorType }
     * 
     */
    public DoorType createDoorType() {
        return new DoorType();
    }

    /**
     * Create an instance of {@link BridgeRoomType }
     * 
     */
    public BridgeRoomType createBridgeRoomType() {
        return new BridgeRoomType();
    }

    /**
     * Create an instance of {@link BridgeFurnitureType }
     * 
     */
    public BridgeFurnitureType createBridgeFurnitureType() {
        return new BridgeFurnitureType();
    }

    /**
     * Create an instance of {@link BridgePartPropertyType }
     * 
     */
    public BridgePartPropertyType createBridgePartPropertyType() {
        return new BridgePartPropertyType();
    }

    /**
     * Create an instance of {@link BridgeInstallationPropertyType }
     * 
     */
    public BridgeInstallationPropertyType createBridgeInstallationPropertyType() {
        return new BridgeInstallationPropertyType();
    }

    /**
     * Create an instance of {@link IntBridgeInstallationPropertyType }
     * 
     */
    public IntBridgeInstallationPropertyType createIntBridgeInstallationPropertyType() {
        return new IntBridgeInstallationPropertyType();
    }

    /**
     * Create an instance of {@link BridgeConstructionElementPropertyType }
     * 
     */
    public BridgeConstructionElementPropertyType createBridgeConstructionElementPropertyType() {
        return new BridgeConstructionElementPropertyType();
    }

    /**
     * Create an instance of {@link BoundarySurfacePropertyType }
     * 
     */
    public BoundarySurfacePropertyType createBoundarySurfacePropertyType() {
        return new BoundarySurfacePropertyType();
    }

    /**
     * Create an instance of {@link OpeningPropertyType }
     * 
     */
    public OpeningPropertyType createOpeningPropertyType() {
        return new OpeningPropertyType();
    }

    /**
     * Create an instance of {@link InteriorBridgeRoomPropertyType }
     * 
     */
    public InteriorBridgeRoomPropertyType createInteriorBridgeRoomPropertyType() {
        return new InteriorBridgeRoomPropertyType();
    }

    /**
     * Create an instance of {@link InteriorFurniturePropertyType }
     * 
     */
    public InteriorFurniturePropertyType createInteriorFurniturePropertyType() {
        return new InteriorFurniturePropertyType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractBridgeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "_AbstractBridge", substitutionHeadNamespace = "http://www.opengis.net/citygml/2.0", substitutionHeadName = "_Site")
    public JAXBElement<AbstractBridgeType> createAbstractBridge(AbstractBridgeType value) {
        return new JAXBElement<AbstractBridgeType>(_AbstractBridge_QNAME, AbstractBridgeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "_GenericApplicationPropertyOfAbstractBridge")
    public JAXBElement<Object> createGenericApplicationPropertyOfAbstractBridge(Object value) {
        return new JAXBElement<Object>(_GenericApplicationPropertyOfAbstractBridge_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BridgeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "Bridge", substitutionHeadNamespace = "http://www.opengis.net/citygml/bridge/2.0", substitutionHeadName = "_AbstractBridge")
    public JAXBElement<BridgeType> createBridge(BridgeType value) {
        return new JAXBElement<BridgeType>(_Bridge_QNAME, BridgeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "_GenericApplicationPropertyOfBridge")
    public JAXBElement<Object> createGenericApplicationPropertyOfBridge(Object value) {
        return new JAXBElement<Object>(_GenericApplicationPropertyOfBridge_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BridgePartType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "BridgePart", substitutionHeadNamespace = "http://www.opengis.net/citygml/bridge/2.0", substitutionHeadName = "_AbstractBridge")
    public JAXBElement<BridgePartType> createBridgePart(BridgePartType value) {
        return new JAXBElement<BridgePartType>(_BridgePart_QNAME, BridgePartType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "_GenericApplicationPropertyOfBridgePart")
    public JAXBElement<Object> createGenericApplicationPropertyOfBridgePart(Object value) {
        return new JAXBElement<Object>(_GenericApplicationPropertyOfBridgePart_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BridgeInstallationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "BridgeInstallation", substitutionHeadNamespace = "http://www.opengis.net/citygml/2.0", substitutionHeadName = "_CityObject")
    public JAXBElement<BridgeInstallationType> createBridgeInstallation(BridgeInstallationType value) {
        return new JAXBElement<BridgeInstallationType>(_BridgeInstallation_QNAME, BridgeInstallationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "_GenericApplicationPropertyOfBridgeInstallation")
    public JAXBElement<Object> createGenericApplicationPropertyOfBridgeInstallation(Object value) {
        return new JAXBElement<Object>(_GenericApplicationPropertyOfBridgeInstallation_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IntBridgeInstallationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "IntBridgeInstallation", substitutionHeadNamespace = "http://www.opengis.net/citygml/2.0", substitutionHeadName = "_CityObject")
    public JAXBElement<IntBridgeInstallationType> createIntBridgeInstallation(IntBridgeInstallationType value) {
        return new JAXBElement<IntBridgeInstallationType>(_IntBridgeInstallation_QNAME, IntBridgeInstallationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "_GenericApplicationPropertyOfIntBridgeInstallation")
    public JAXBElement<Object> createGenericApplicationPropertyOfIntBridgeInstallation(Object value) {
        return new JAXBElement<Object>(_GenericApplicationPropertyOfIntBridgeInstallation_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BridgeConstructionElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "BridgeConstructionElement", substitutionHeadNamespace = "http://www.opengis.net/citygml/2.0", substitutionHeadName = "_CityObject")
    public JAXBElement<BridgeConstructionElementType> createBridgeConstructionElement(BridgeConstructionElementType value) {
        return new JAXBElement<BridgeConstructionElementType>(_BridgeConstructionElement_QNAME, BridgeConstructionElementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "_GenericApplicationPropertyOfBridgeConstructionElement")
    public JAXBElement<Object> createGenericApplicationPropertyOfBridgeConstructionElement(Object value) {
        return new JAXBElement<Object>(_GenericApplicationPropertyOfBridgeConstructionElement_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractBoundarySurfaceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "_BoundarySurface", substitutionHeadNamespace = "http://www.opengis.net/citygml/2.0", substitutionHeadName = "_CityObject")
    public JAXBElement<AbstractBoundarySurfaceType> createBoundarySurface(AbstractBoundarySurfaceType value) {
        return new JAXBElement<AbstractBoundarySurfaceType>(_BoundarySurface_QNAME, AbstractBoundarySurfaceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "_GenericApplicationPropertyOfBoundarySurface")
    public JAXBElement<Object> createGenericApplicationPropertyOfBoundarySurface(Object value) {
        return new JAXBElement<Object>(_GenericApplicationPropertyOfBoundarySurface_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RoofSurfaceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "RoofSurface", substitutionHeadNamespace = "http://www.opengis.net/citygml/bridge/2.0", substitutionHeadName = "_BoundarySurface")
    public JAXBElement<RoofSurfaceType> createRoofSurface(RoofSurfaceType value) {
        return new JAXBElement<RoofSurfaceType>(_RoofSurface_QNAME, RoofSurfaceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "_GenericApplicationPropertyOfRoofSurface")
    public JAXBElement<Object> createGenericApplicationPropertyOfRoofSurface(Object value) {
        return new JAXBElement<Object>(_GenericApplicationPropertyOfRoofSurface_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WallSurfaceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "WallSurface", substitutionHeadNamespace = "http://www.opengis.net/citygml/bridge/2.0", substitutionHeadName = "_BoundarySurface")
    public JAXBElement<WallSurfaceType> createWallSurface(WallSurfaceType value) {
        return new JAXBElement<WallSurfaceType>(_WallSurface_QNAME, WallSurfaceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "_GenericApplicationPropertyOfWallSurface")
    public JAXBElement<Object> createGenericApplicationPropertyOfWallSurface(Object value) {
        return new JAXBElement<Object>(_GenericApplicationPropertyOfWallSurface_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GroundSurfaceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "GroundSurface", substitutionHeadNamespace = "http://www.opengis.net/citygml/bridge/2.0", substitutionHeadName = "_BoundarySurface")
    public JAXBElement<GroundSurfaceType> createGroundSurface(GroundSurfaceType value) {
        return new JAXBElement<GroundSurfaceType>(_GroundSurface_QNAME, GroundSurfaceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "_GenericApplicationPropertyOfGroundSurface")
    public JAXBElement<Object> createGenericApplicationPropertyOfGroundSurface(Object value) {
        return new JAXBElement<Object>(_GenericApplicationPropertyOfGroundSurface_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClosureSurfaceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "ClosureSurface", substitutionHeadNamespace = "http://www.opengis.net/citygml/bridge/2.0", substitutionHeadName = "_BoundarySurface")
    public JAXBElement<ClosureSurfaceType> createClosureSurface(ClosureSurfaceType value) {
        return new JAXBElement<ClosureSurfaceType>(_ClosureSurface_QNAME, ClosureSurfaceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "_GenericApplicationPropertyOfClosureSurface")
    public JAXBElement<Object> createGenericApplicationPropertyOfClosureSurface(Object value) {
        return new JAXBElement<Object>(_GenericApplicationPropertyOfClosureSurface_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OuterFloorSurfaceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "OuterFloorSurface", substitutionHeadNamespace = "http://www.opengis.net/citygml/bridge/2.0", substitutionHeadName = "_BoundarySurface")
    public JAXBElement<OuterFloorSurfaceType> createOuterFloorSurface(OuterFloorSurfaceType value) {
        return new JAXBElement<OuterFloorSurfaceType>(_OuterFloorSurface_QNAME, OuterFloorSurfaceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "_GenericApplicationPropertyOfOuterFloorSurface")
    public JAXBElement<Object> createGenericApplicationPropertyOfOuterFloorSurface(Object value) {
        return new JAXBElement<Object>(_GenericApplicationPropertyOfOuterFloorSurface_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OuterCeilingSurfaceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "OuterCeilingSurface", substitutionHeadNamespace = "http://www.opengis.net/citygml/bridge/2.0", substitutionHeadName = "_BoundarySurface")
    public JAXBElement<OuterCeilingSurfaceType> createOuterCeilingSurface(OuterCeilingSurfaceType value) {
        return new JAXBElement<OuterCeilingSurfaceType>(_OuterCeilingSurface_QNAME, OuterCeilingSurfaceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "_GenericApplicationPropertyOfOuterCeilingSurface")
    public JAXBElement<Object> createGenericApplicationPropertyOfOuterCeilingSurface(Object value) {
        return new JAXBElement<Object>(_GenericApplicationPropertyOfOuterCeilingSurface_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FloorSurfaceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "FloorSurface", substitutionHeadNamespace = "http://www.opengis.net/citygml/bridge/2.0", substitutionHeadName = "_BoundarySurface")
    public JAXBElement<FloorSurfaceType> createFloorSurface(FloorSurfaceType value) {
        return new JAXBElement<FloorSurfaceType>(_FloorSurface_QNAME, FloorSurfaceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "_GenericApplicationPropertyOfFloorSurface")
    public JAXBElement<Object> createGenericApplicationPropertyOfFloorSurface(Object value) {
        return new JAXBElement<Object>(_GenericApplicationPropertyOfFloorSurface_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InteriorWallSurfaceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "InteriorWallSurface", substitutionHeadNamespace = "http://www.opengis.net/citygml/bridge/2.0", substitutionHeadName = "_BoundarySurface")
    public JAXBElement<InteriorWallSurfaceType> createInteriorWallSurface(InteriorWallSurfaceType value) {
        return new JAXBElement<InteriorWallSurfaceType>(_InteriorWallSurface_QNAME, InteriorWallSurfaceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "_GenericApplicationPropertyOfInteriorWallSurface")
    public JAXBElement<Object> createGenericApplicationPropertyOfInteriorWallSurface(Object value) {
        return new JAXBElement<Object>(_GenericApplicationPropertyOfInteriorWallSurface_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CeilingSurfaceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "CeilingSurface", substitutionHeadNamespace = "http://www.opengis.net/citygml/bridge/2.0", substitutionHeadName = "_BoundarySurface")
    public JAXBElement<CeilingSurfaceType> createCeilingSurface(CeilingSurfaceType value) {
        return new JAXBElement<CeilingSurfaceType>(_CeilingSurface_QNAME, CeilingSurfaceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "_GenericApplicationPropertyOfCeilingSurface")
    public JAXBElement<Object> createGenericApplicationPropertyOfCeilingSurface(Object value) {
        return new JAXBElement<Object>(_GenericApplicationPropertyOfCeilingSurface_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractOpeningType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "_Opening", substitutionHeadNamespace = "http://www.opengis.net/citygml/2.0", substitutionHeadName = "_CityObject")
    public JAXBElement<AbstractOpeningType> createOpening(AbstractOpeningType value) {
        return new JAXBElement<AbstractOpeningType>(_Opening_QNAME, AbstractOpeningType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "_GenericApplicationPropertyOfOpening")
    public JAXBElement<Object> createGenericApplicationPropertyOfOpening(Object value) {
        return new JAXBElement<Object>(_GenericApplicationPropertyOfOpening_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WindowType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "Window", substitutionHeadNamespace = "http://www.opengis.net/citygml/bridge/2.0", substitutionHeadName = "_Opening")
    public JAXBElement<WindowType> createWindow(WindowType value) {
        return new JAXBElement<WindowType>(_Window_QNAME, WindowType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "_GenericApplicationPropertyOfWindow")
    public JAXBElement<Object> createGenericApplicationPropertyOfWindow(Object value) {
        return new JAXBElement<Object>(_GenericApplicationPropertyOfWindow_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DoorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "Door", substitutionHeadNamespace = "http://www.opengis.net/citygml/bridge/2.0", substitutionHeadName = "_Opening")
    public JAXBElement<DoorType> createDoor(DoorType value) {
        return new JAXBElement<DoorType>(_Door_QNAME, DoorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "_GenericApplicationPropertyOfDoor")
    public JAXBElement<Object> createGenericApplicationPropertyOfDoor(Object value) {
        return new JAXBElement<Object>(_GenericApplicationPropertyOfDoor_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BridgeRoomType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "BridgeRoom", substitutionHeadNamespace = "http://www.opengis.net/citygml/2.0", substitutionHeadName = "_CityObject")
    public JAXBElement<BridgeRoomType> createBridgeRoom(BridgeRoomType value) {
        return new JAXBElement<BridgeRoomType>(_BridgeRoom_QNAME, BridgeRoomType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "_GenericApplicationPropertyOfBridgeRoom")
    public JAXBElement<Object> createGenericApplicationPropertyOfBridgeRoom(Object value) {
        return new JAXBElement<Object>(_GenericApplicationPropertyOfBridgeRoom_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BridgeFurnitureType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "BridgeFurniture", substitutionHeadNamespace = "http://www.opengis.net/citygml/2.0", substitutionHeadName = "_CityObject")
    public JAXBElement<BridgeFurnitureType> createBridgeFurniture(BridgeFurnitureType value) {
        return new JAXBElement<BridgeFurnitureType>(_BridgeFurniture_QNAME, BridgeFurnitureType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/citygml/bridge/2.0", name = "_GenericApplicationPropertyOfBridgeFurniture")
    public JAXBElement<Object> createGenericApplicationPropertyOfBridgeFurniture(Object value) {
        return new JAXBElement<Object>(_GenericApplicationPropertyOfBridgeFurniture_QNAME, Object.class, null, value);
    }

}
