//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.10 at 10:41:43 AM KST 
//


package net.opengis.citygml.tunnel.v_2_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.CopyStrategy;
import org.jvnet.jaxb2_commons.lang.CopyTo;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * Mostly vertical construction that bounds a HollowSpace.
 * 
 * <p>Java class for InteriorWallSurfaceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InteriorWallSurfaceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.opengis.net/citygml/tunnel/2.0}AbstractBoundarySurfaceType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.opengis.net/citygml/tunnel/2.0}_GenericApplicationPropertyOfInteriorWallSurface" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InteriorWallSurfaceType", propOrder = {
    "genericApplicationPropertyOfInteriorWallSurface"
})
public class InteriorWallSurfaceType
    extends AbstractBoundarySurfaceType
    implements Cloneable, CopyTo, Equals, HashCode, ToString
{

    @XmlElement(name = "_GenericApplicationPropertyOfInteriorWallSurface")
    protected List<Object> genericApplicationPropertyOfInteriorWallSurface;

    /**
     * Gets the value of the genericApplicationPropertyOfInteriorWallSurface property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the genericApplicationPropertyOfInteriorWallSurface property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGenericApplicationPropertyOfInteriorWallSurface().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getGenericApplicationPropertyOfInteriorWallSurface() {
        if (genericApplicationPropertyOfInteriorWallSurface == null) {
            genericApplicationPropertyOfInteriorWallSurface = new ArrayList<Object>();
        }
        return this.genericApplicationPropertyOfInteriorWallSurface;
    }

    public boolean isSetGenericApplicationPropertyOfInteriorWallSurface() {
        return ((this.genericApplicationPropertyOfInteriorWallSurface!= null)&&(!this.genericApplicationPropertyOfInteriorWallSurface.isEmpty()));
    }

    public void unsetGenericApplicationPropertyOfInteriorWallSurface() {
        this.genericApplicationPropertyOfInteriorWallSurface = null;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        super.appendFields(locator, buffer, strategy);
        {
            List<Object> theGenericApplicationPropertyOfInteriorWallSurface;
            theGenericApplicationPropertyOfInteriorWallSurface = (this.isSetGenericApplicationPropertyOfInteriorWallSurface()?this.getGenericApplicationPropertyOfInteriorWallSurface():null);
            strategy.appendField(locator, this, "genericApplicationPropertyOfInteriorWallSurface", buffer, theGenericApplicationPropertyOfInteriorWallSurface);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof InteriorWallSurfaceType)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final InteriorWallSurfaceType that = ((InteriorWallSurfaceType) object);
        {
            List<Object> lhsGenericApplicationPropertyOfInteriorWallSurface;
            lhsGenericApplicationPropertyOfInteriorWallSurface = (this.isSetGenericApplicationPropertyOfInteriorWallSurface()?this.getGenericApplicationPropertyOfInteriorWallSurface():null);
            List<Object> rhsGenericApplicationPropertyOfInteriorWallSurface;
            rhsGenericApplicationPropertyOfInteriorWallSurface = (that.isSetGenericApplicationPropertyOfInteriorWallSurface()?that.getGenericApplicationPropertyOfInteriorWallSurface():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "genericApplicationPropertyOfInteriorWallSurface", lhsGenericApplicationPropertyOfInteriorWallSurface), LocatorUtils.property(thatLocator, "genericApplicationPropertyOfInteriorWallSurface", rhsGenericApplicationPropertyOfInteriorWallSurface), lhsGenericApplicationPropertyOfInteriorWallSurface, rhsGenericApplicationPropertyOfInteriorWallSurface)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            List<Object> theGenericApplicationPropertyOfInteriorWallSurface;
            theGenericApplicationPropertyOfInteriorWallSurface = (this.isSetGenericApplicationPropertyOfInteriorWallSurface()?this.getGenericApplicationPropertyOfInteriorWallSurface():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "genericApplicationPropertyOfInteriorWallSurface", theGenericApplicationPropertyOfInteriorWallSurface), currentHashCode, theGenericApplicationPropertyOfInteriorWallSurface);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        super.copyTo(locator, draftCopy, strategy);
        if (draftCopy instanceof InteriorWallSurfaceType) {
            final InteriorWallSurfaceType copy = ((InteriorWallSurfaceType) draftCopy);
            if (this.isSetGenericApplicationPropertyOfInteriorWallSurface()) {
                List<Object> sourceGenericApplicationPropertyOfInteriorWallSurface;
                sourceGenericApplicationPropertyOfInteriorWallSurface = (this.isSetGenericApplicationPropertyOfInteriorWallSurface()?this.getGenericApplicationPropertyOfInteriorWallSurface():null);
                @SuppressWarnings("unchecked")
                List<Object> copyGenericApplicationPropertyOfInteriorWallSurface = ((List<Object> ) strategy.copy(LocatorUtils.property(locator, "genericApplicationPropertyOfInteriorWallSurface", sourceGenericApplicationPropertyOfInteriorWallSurface), sourceGenericApplicationPropertyOfInteriorWallSurface));
                copy.unsetGenericApplicationPropertyOfInteriorWallSurface();
                if (copyGenericApplicationPropertyOfInteriorWallSurface!= null) {
                    List<Object> uniqueGenericApplicationPropertyOfInteriorWallSurfacel = copy.getGenericApplicationPropertyOfInteriorWallSurface();
                    uniqueGenericApplicationPropertyOfInteriorWallSurfacel.addAll(copyGenericApplicationPropertyOfInteriorWallSurface);
                }
            } else {
                copy.unsetGenericApplicationPropertyOfInteriorWallSurface();
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new InteriorWallSurfaceType();
    }

}
