//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.10 at 10:41:43 AM KST 
//


package net.opengis.citygml.tunnel.v_2_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.CopyStrategy;
import org.jvnet.jaxb2_commons.lang.CopyTo;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * Horizontal construction that separates the interior part of the Tunnel from the ambient medium (rock,
 * 				earth, water, air, ..) from below.
 * 
 * <p>Java class for OuterFloorSurfaceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OuterFloorSurfaceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.opengis.net/citygml/tunnel/2.0}AbstractBoundarySurfaceType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.opengis.net/citygml/tunnel/2.0}_GenericApplicationPropertyOfOuterFloorSurface" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OuterFloorSurfaceType", propOrder = {
    "genericApplicationPropertyOfOuterFloorSurface"
})
public class OuterFloorSurfaceType
    extends AbstractBoundarySurfaceType
    implements Cloneable, CopyTo, Equals, HashCode, ToString
{

    @XmlElement(name = "_GenericApplicationPropertyOfOuterFloorSurface")
    protected List<Object> genericApplicationPropertyOfOuterFloorSurface;

    /**
     * Gets the value of the genericApplicationPropertyOfOuterFloorSurface property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the genericApplicationPropertyOfOuterFloorSurface property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGenericApplicationPropertyOfOuterFloorSurface().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getGenericApplicationPropertyOfOuterFloorSurface() {
        if (genericApplicationPropertyOfOuterFloorSurface == null) {
            genericApplicationPropertyOfOuterFloorSurface = new ArrayList<Object>();
        }
        return this.genericApplicationPropertyOfOuterFloorSurface;
    }

    public boolean isSetGenericApplicationPropertyOfOuterFloorSurface() {
        return ((this.genericApplicationPropertyOfOuterFloorSurface!= null)&&(!this.genericApplicationPropertyOfOuterFloorSurface.isEmpty()));
    }

    public void unsetGenericApplicationPropertyOfOuterFloorSurface() {
        this.genericApplicationPropertyOfOuterFloorSurface = null;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        super.appendFields(locator, buffer, strategy);
        {
            List<Object> theGenericApplicationPropertyOfOuterFloorSurface;
            theGenericApplicationPropertyOfOuterFloorSurface = (this.isSetGenericApplicationPropertyOfOuterFloorSurface()?this.getGenericApplicationPropertyOfOuterFloorSurface():null);
            strategy.appendField(locator, this, "genericApplicationPropertyOfOuterFloorSurface", buffer, theGenericApplicationPropertyOfOuterFloorSurface);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof OuterFloorSurfaceType)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final OuterFloorSurfaceType that = ((OuterFloorSurfaceType) object);
        {
            List<Object> lhsGenericApplicationPropertyOfOuterFloorSurface;
            lhsGenericApplicationPropertyOfOuterFloorSurface = (this.isSetGenericApplicationPropertyOfOuterFloorSurface()?this.getGenericApplicationPropertyOfOuterFloorSurface():null);
            List<Object> rhsGenericApplicationPropertyOfOuterFloorSurface;
            rhsGenericApplicationPropertyOfOuterFloorSurface = (that.isSetGenericApplicationPropertyOfOuterFloorSurface()?that.getGenericApplicationPropertyOfOuterFloorSurface():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "genericApplicationPropertyOfOuterFloorSurface", lhsGenericApplicationPropertyOfOuterFloorSurface), LocatorUtils.property(thatLocator, "genericApplicationPropertyOfOuterFloorSurface", rhsGenericApplicationPropertyOfOuterFloorSurface), lhsGenericApplicationPropertyOfOuterFloorSurface, rhsGenericApplicationPropertyOfOuterFloorSurface)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            List<Object> theGenericApplicationPropertyOfOuterFloorSurface;
            theGenericApplicationPropertyOfOuterFloorSurface = (this.isSetGenericApplicationPropertyOfOuterFloorSurface()?this.getGenericApplicationPropertyOfOuterFloorSurface():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "genericApplicationPropertyOfOuterFloorSurface", theGenericApplicationPropertyOfOuterFloorSurface), currentHashCode, theGenericApplicationPropertyOfOuterFloorSurface);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        super.copyTo(locator, draftCopy, strategy);
        if (draftCopy instanceof OuterFloorSurfaceType) {
            final OuterFloorSurfaceType copy = ((OuterFloorSurfaceType) draftCopy);
            if (this.isSetGenericApplicationPropertyOfOuterFloorSurface()) {
                List<Object> sourceGenericApplicationPropertyOfOuterFloorSurface;
                sourceGenericApplicationPropertyOfOuterFloorSurface = (this.isSetGenericApplicationPropertyOfOuterFloorSurface()?this.getGenericApplicationPropertyOfOuterFloorSurface():null);
                @SuppressWarnings("unchecked")
                List<Object> copyGenericApplicationPropertyOfOuterFloorSurface = ((List<Object> ) strategy.copy(LocatorUtils.property(locator, "genericApplicationPropertyOfOuterFloorSurface", sourceGenericApplicationPropertyOfOuterFloorSurface), sourceGenericApplicationPropertyOfOuterFloorSurface));
                copy.unsetGenericApplicationPropertyOfOuterFloorSurface();
                if (copyGenericApplicationPropertyOfOuterFloorSurface!= null) {
                    List<Object> uniqueGenericApplicationPropertyOfOuterFloorSurfacel = copy.getGenericApplicationPropertyOfOuterFloorSurface();
                    uniqueGenericApplicationPropertyOfOuterFloorSurfacel.addAll(copyGenericApplicationPropertyOfOuterFloorSurface);
                }
            } else {
                copy.unsetGenericApplicationPropertyOfOuterFloorSurface();
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new OuterFloorSurfaceType();
    }

}
