//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.10 at 10:41:43 AM KST 
//


package net.opengis.gml.v_3_1_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import org.jvnet.jaxb2_commons.lang.CopyStrategy;
import org.jvnet.jaxb2_commons.lang.CopyTo;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * Used to vary individual graphic parameters and attributes of the style, symbol or text.
 * 
 * <p>Java class for StyleVariationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StyleVariationType"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *       &lt;attribute name="styleProperty" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="featurePropertyRange" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StyleVariationType", propOrder = {
    "value"
})
public class StyleVariationType
    implements Cloneable, CopyTo, Equals, HashCode, ToString
{

    @XmlValue
    protected String value;
    @XmlAttribute(name = "styleProperty", required = true)
    protected String styleProperty;
    @XmlAttribute(name = "featurePropertyRange")
    protected String featurePropertyRange;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    public boolean isSetValue() {
        return (this.value!= null);
    }

    /**
     * Gets the value of the styleProperty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStyleProperty() {
        return styleProperty;
    }

    /**
     * Sets the value of the styleProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStyleProperty(String value) {
        this.styleProperty = value;
    }

    public boolean isSetStyleProperty() {
        return (this.styleProperty!= null);
    }

    /**
     * Gets the value of the featurePropertyRange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeaturePropertyRange() {
        return featurePropertyRange;
    }

    /**
     * Sets the value of the featurePropertyRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeaturePropertyRange(String value) {
        this.featurePropertyRange = value;
    }

    public boolean isSetFeaturePropertyRange() {
        return (this.featurePropertyRange!= null);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theValue;
            theValue = this.getValue();
            strategy.appendField(locator, this, "value", buffer, theValue);
        }
        {
            String theStyleProperty;
            theStyleProperty = this.getStyleProperty();
            strategy.appendField(locator, this, "styleProperty", buffer, theStyleProperty);
        }
        {
            String theFeaturePropertyRange;
            theFeaturePropertyRange = this.getFeaturePropertyRange();
            strategy.appendField(locator, this, "featurePropertyRange", buffer, theFeaturePropertyRange);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof StyleVariationType)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final StyleVariationType that = ((StyleVariationType) object);
        {
            String lhsValue;
            lhsValue = this.getValue();
            String rhsValue;
            rhsValue = that.getValue();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "value", lhsValue), LocatorUtils.property(thatLocator, "value", rhsValue), lhsValue, rhsValue)) {
                return false;
            }
        }
        {
            String lhsStyleProperty;
            lhsStyleProperty = this.getStyleProperty();
            String rhsStyleProperty;
            rhsStyleProperty = that.getStyleProperty();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "styleProperty", lhsStyleProperty), LocatorUtils.property(thatLocator, "styleProperty", rhsStyleProperty), lhsStyleProperty, rhsStyleProperty)) {
                return false;
            }
        }
        {
            String lhsFeaturePropertyRange;
            lhsFeaturePropertyRange = this.getFeaturePropertyRange();
            String rhsFeaturePropertyRange;
            rhsFeaturePropertyRange = that.getFeaturePropertyRange();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "featurePropertyRange", lhsFeaturePropertyRange), LocatorUtils.property(thatLocator, "featurePropertyRange", rhsFeaturePropertyRange), lhsFeaturePropertyRange, rhsFeaturePropertyRange)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            String theValue;
            theValue = this.getValue();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "value", theValue), currentHashCode, theValue);
        }
        {
            String theStyleProperty;
            theStyleProperty = this.getStyleProperty();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "styleProperty", theStyleProperty), currentHashCode, theStyleProperty);
        }
        {
            String theFeaturePropertyRange;
            theFeaturePropertyRange = this.getFeaturePropertyRange();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "featurePropertyRange", theFeaturePropertyRange), currentHashCode, theFeaturePropertyRange);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        if (draftCopy instanceof StyleVariationType) {
            final StyleVariationType copy = ((StyleVariationType) draftCopy);
            if (this.isSetValue()) {
                String sourceValue;
                sourceValue = this.getValue();
                String copyValue = ((String) strategy.copy(LocatorUtils.property(locator, "value", sourceValue), sourceValue));
                copy.setValue(copyValue);
            } else {
                copy.value = null;
            }
            if (this.isSetStyleProperty()) {
                String sourceStyleProperty;
                sourceStyleProperty = this.getStyleProperty();
                String copyStyleProperty = ((String) strategy.copy(LocatorUtils.property(locator, "styleProperty", sourceStyleProperty), sourceStyleProperty));
                copy.setStyleProperty(copyStyleProperty);
            } else {
                copy.styleProperty = null;
            }
            if (this.isSetFeaturePropertyRange()) {
                String sourceFeaturePropertyRange;
                sourceFeaturePropertyRange = this.getFeaturePropertyRange();
                String copyFeaturePropertyRange = ((String) strategy.copy(LocatorUtils.property(locator, "featurePropertyRange", sourceFeaturePropertyRange), sourceFeaturePropertyRange));
                copy.setFeaturePropertyRange(copyFeaturePropertyRange);
            } else {
                copy.featurePropertyRange = null;
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new StyleVariationType();
    }

}
