//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.10 at 10:41:43 AM KST 
//


package net.opengis.gml.v_3_1_1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.jvnet.jaxb2_commons.lang.CopyStrategy;
import org.jvnet.jaxb2_commons.lang.CopyTo;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * A clock provides a basis for defining temporal position within a day. 
 *       A clock must be used with a calendar in order to provide a complete description of a temporal position 
 *       within a specific day.
 * 
 * <p>Java class for TimeClockType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TimeClockType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.opengis.net/gml}AbstractTimeReferenceSystemType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="referenceEvent" type="{http://www.opengis.net/gml}StringOrRefType"/&gt;
 *         &lt;element name="referenceTime" type="{http://www.w3.org/2001/XMLSchema}time"/&gt;
 *         &lt;element name="utcReference" type="{http://www.w3.org/2001/XMLSchema}time"/&gt;
 *         &lt;element name="dateBasis" type="{http://www.opengis.net/gml}TimeCalendarPropertyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimeClockType", propOrder = {
    "referenceEvent",
    "referenceTime",
    "utcReference",
    "dateBasis"
})
public class TimeClockType
    extends AbstractTimeReferenceSystemType
    implements Cloneable, CopyTo, Equals, HashCode, ToString
{

    @XmlElement(required = true)
    protected StringOrRefType referenceEvent;
    @XmlElement(required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar referenceTime;
    @XmlElement(required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar utcReference;
    protected List<TimeCalendarPropertyType> dateBasis;

    /**
     * Gets the value of the referenceEvent property.
     * 
     * @return
     *     possible object is
     *     {@link StringOrRefType }
     *     
     */
    public StringOrRefType getReferenceEvent() {
        return referenceEvent;
    }

    /**
     * Sets the value of the referenceEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringOrRefType }
     *     
     */
    public void setReferenceEvent(StringOrRefType value) {
        this.referenceEvent = value;
    }

    public boolean isSetReferenceEvent() {
        return (this.referenceEvent!= null);
    }

    /**
     * Gets the value of the referenceTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReferenceTime() {
        return referenceTime;
    }

    /**
     * Sets the value of the referenceTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReferenceTime(XMLGregorianCalendar value) {
        this.referenceTime = value;
    }

    public boolean isSetReferenceTime() {
        return (this.referenceTime!= null);
    }

    /**
     * Gets the value of the utcReference property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUtcReference() {
        return utcReference;
    }

    /**
     * Sets the value of the utcReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUtcReference(XMLGregorianCalendar value) {
        this.utcReference = value;
    }

    public boolean isSetUtcReference() {
        return (this.utcReference!= null);
    }

    /**
     * Gets the value of the dateBasis property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dateBasis property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDateBasis().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TimeCalendarPropertyType }
     * 
     * 
     */
    public List<TimeCalendarPropertyType> getDateBasis() {
        if (dateBasis == null) {
            dateBasis = new ArrayList<TimeCalendarPropertyType>();
        }
        return this.dateBasis;
    }

    public boolean isSetDateBasis() {
        return ((this.dateBasis!= null)&&(!this.dateBasis.isEmpty()));
    }

    public void unsetDateBasis() {
        this.dateBasis = null;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        super.appendFields(locator, buffer, strategy);
        {
            StringOrRefType theReferenceEvent;
            theReferenceEvent = this.getReferenceEvent();
            strategy.appendField(locator, this, "referenceEvent", buffer, theReferenceEvent);
        }
        {
            XMLGregorianCalendar theReferenceTime;
            theReferenceTime = this.getReferenceTime();
            strategy.appendField(locator, this, "referenceTime", buffer, theReferenceTime);
        }
        {
            XMLGregorianCalendar theUtcReference;
            theUtcReference = this.getUtcReference();
            strategy.appendField(locator, this, "utcReference", buffer, theUtcReference);
        }
        {
            List<TimeCalendarPropertyType> theDateBasis;
            theDateBasis = (this.isSetDateBasis()?this.getDateBasis():null);
            strategy.appendField(locator, this, "dateBasis", buffer, theDateBasis);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof TimeClockType)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final TimeClockType that = ((TimeClockType) object);
        {
            StringOrRefType lhsReferenceEvent;
            lhsReferenceEvent = this.getReferenceEvent();
            StringOrRefType rhsReferenceEvent;
            rhsReferenceEvent = that.getReferenceEvent();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "referenceEvent", lhsReferenceEvent), LocatorUtils.property(thatLocator, "referenceEvent", rhsReferenceEvent), lhsReferenceEvent, rhsReferenceEvent)) {
                return false;
            }
        }
        {
            XMLGregorianCalendar lhsReferenceTime;
            lhsReferenceTime = this.getReferenceTime();
            XMLGregorianCalendar rhsReferenceTime;
            rhsReferenceTime = that.getReferenceTime();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "referenceTime", lhsReferenceTime), LocatorUtils.property(thatLocator, "referenceTime", rhsReferenceTime), lhsReferenceTime, rhsReferenceTime)) {
                return false;
            }
        }
        {
            XMLGregorianCalendar lhsUtcReference;
            lhsUtcReference = this.getUtcReference();
            XMLGregorianCalendar rhsUtcReference;
            rhsUtcReference = that.getUtcReference();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "utcReference", lhsUtcReference), LocatorUtils.property(thatLocator, "utcReference", rhsUtcReference), lhsUtcReference, rhsUtcReference)) {
                return false;
            }
        }
        {
            List<TimeCalendarPropertyType> lhsDateBasis;
            lhsDateBasis = (this.isSetDateBasis()?this.getDateBasis():null);
            List<TimeCalendarPropertyType> rhsDateBasis;
            rhsDateBasis = (that.isSetDateBasis()?that.getDateBasis():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "dateBasis", lhsDateBasis), LocatorUtils.property(thatLocator, "dateBasis", rhsDateBasis), lhsDateBasis, rhsDateBasis)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            StringOrRefType theReferenceEvent;
            theReferenceEvent = this.getReferenceEvent();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "referenceEvent", theReferenceEvent), currentHashCode, theReferenceEvent);
        }
        {
            XMLGregorianCalendar theReferenceTime;
            theReferenceTime = this.getReferenceTime();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "referenceTime", theReferenceTime), currentHashCode, theReferenceTime);
        }
        {
            XMLGregorianCalendar theUtcReference;
            theUtcReference = this.getUtcReference();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "utcReference", theUtcReference), currentHashCode, theUtcReference);
        }
        {
            List<TimeCalendarPropertyType> theDateBasis;
            theDateBasis = (this.isSetDateBasis()?this.getDateBasis():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "dateBasis", theDateBasis), currentHashCode, theDateBasis);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        super.copyTo(locator, draftCopy, strategy);
        if (draftCopy instanceof TimeClockType) {
            final TimeClockType copy = ((TimeClockType) draftCopy);
            if (this.isSetReferenceEvent()) {
                StringOrRefType sourceReferenceEvent;
                sourceReferenceEvent = this.getReferenceEvent();
                StringOrRefType copyReferenceEvent = ((StringOrRefType) strategy.copy(LocatorUtils.property(locator, "referenceEvent", sourceReferenceEvent), sourceReferenceEvent));
                copy.setReferenceEvent(copyReferenceEvent);
            } else {
                copy.referenceEvent = null;
            }
            if (this.isSetReferenceTime()) {
                XMLGregorianCalendar sourceReferenceTime;
                sourceReferenceTime = this.getReferenceTime();
                XMLGregorianCalendar copyReferenceTime = ((XMLGregorianCalendar) strategy.copy(LocatorUtils.property(locator, "referenceTime", sourceReferenceTime), sourceReferenceTime));
                copy.setReferenceTime(copyReferenceTime);
            } else {
                copy.referenceTime = null;
            }
            if (this.isSetUtcReference()) {
                XMLGregorianCalendar sourceUtcReference;
                sourceUtcReference = this.getUtcReference();
                XMLGregorianCalendar copyUtcReference = ((XMLGregorianCalendar) strategy.copy(LocatorUtils.property(locator, "utcReference", sourceUtcReference), sourceUtcReference));
                copy.setUtcReference(copyUtcReference);
            } else {
                copy.utcReference = null;
            }
            if (this.isSetDateBasis()) {
                List<TimeCalendarPropertyType> sourceDateBasis;
                sourceDateBasis = (this.isSetDateBasis()?this.getDateBasis():null);
                @SuppressWarnings("unchecked")
                List<TimeCalendarPropertyType> copyDateBasis = ((List<TimeCalendarPropertyType> ) strategy.copy(LocatorUtils.property(locator, "dateBasis", sourceDateBasis), sourceDateBasis));
                copy.unsetDateBasis();
                if (copyDateBasis!= null) {
                    List<TimeCalendarPropertyType> uniqueDateBasisl = copy.getDateBasis();
                    uniqueDateBasisl.addAll(copyDateBasis);
                }
            } else {
                copy.unsetDateBasis();
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new TimeClockType();
    }

}
